import {
    Register,
    ConfirmEmail,
    SendPasswordResetEmail,
    ResetPassword,
    Login,
    LogOut,
    Refresh,
    ChangeRole,
    UploadUserAvatar,
    FetchAllDoctors,
    FetchDoctorById,
    FetchAllComments,
    UploadComment,
    LikeOrDislikeComment,
    FetchAllProfessions,
    FetchDoctorByAuth,
    CreateOrUpdateDoctor,
    CreateProfession,
} from './endpoints'

export {
    Register,
    ConfirmEmail,
    SendPasswordResetEmail,
    ResetPassword,
    Login,
    LogOut,
    Refresh,
    ChangeRole,
    UploadUserAvatar,
    FetchAllDoctors,
    FetchDoctorById,
    FetchAllComments,
    UploadComment,
    LikeOrDislikeComment,
    FetchAllProfessions,
    FetchDoctorByAuth,
    CreateOrUpdateDoctor,
    CreateProfession,
};